### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by s7an1slaw** [spigotplugins/fakeplayer#12]
Hello, is it possible to make it so that if someone wants to teleport or write a personal message to the fake player, it does not say that there is no such player, but to send the message. Thanks in advance.
![Screenshot_1105](https://user-images.githubusercontent.com/67442642/97790197-43867e80-1bcf-11eb-8e66-8eaf8b320619.png)

**Comment by s7an1slaw** [comment]
Hi again, I searched the plugin and found 2 problems. Picture 1. The first is that when you add a fake player with a name, in this case it is "" then when a real player tries to enter the server it releases it and not as usual in picture 2 to stop it and write to it (There is already a user playing on the server with the same username!). The second problem is that when I create a fake player and then a real player enters the server and does not respect it in the counting in the tab list. Picture 3,4,5.
![1](https://user-images.githubusercontent.com/67442642/97798173-6004d400-1c2c-11eb-8ed4-e5783e9ca88d.png)
![2](https://user-images.githubusercontent.com/67442642/97798175-61ce9780-1c2c-11eb-99c0-c2fd811aa1da.png)
![3](https://user-images.githubusercontent.com/67442642/97798176-6430f180-1c2c-11eb-9e14-ec082c3a972a.png)
![4](https://user-images.githubusercontent.com/67442642/97798178-65621e80-1c2c-11eb-8d93-1eda0b12fa8e.png)
![5](https://user-images.githubusercontent.com/67442642/97798180-66934b80-1c2c-11eb-9063-2cc88e507b64.png)

**Comment by portlek** [comment]
thanks for report the issues and requests.

**Comment by s7an1slaw** [comment]
Hello can i just ask when you will make the changes, sorry for the inconvenience

**Comment by portlek** [comment]
I really don't know, I have not enough time to solve issues or adding new features; maybe someone who's a developer can solve these issues but I can't for now.
