### ISSUE TITLE
1.16.4 update request

### ISSUE THREAD

**Issue by GriffinChen** [spigotplugins/fakeplayer#15]
Hi, the FakePlayer Plugin is not working on 1.16.4 Spigot and Paper server-client, please update to the latest version, thank you so much for that. 

On 1.16.4 servers, I can only open the GUI, but when I click "Add fake players", nothing happened.

This is really a great plugin when it is combined with "HoldEntities" because players can move those fake players to somewhere so that they don't need to AFK by themselves.

**Comment by portlek** [comment]
#14 duplicate.
