### ISSUE TITLE
What should I do if I want to build it by myself

### ISSUE THREAD

**Issue by taooceros** [spigotplugins/fakeplayer#2]
I am really interested in how you implement the function of this plugin and if possible, I would love to provide some help in the plugin if possible.
However, I am unable to build the plugin by maven (I am somehow new to maven).

**Comment by portlek** [comment]
https://www.youtube.com/watch?v=6AVC3X88z6E
You can watch that video ^^

**Comment by taooceros** [comment]
Thanks! I will take a look on that! 😉😉😉😉😉
